### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by Bryan-Legend** [dioveath/sudokumania#1]
Hello Saroj,

Thanks for creating this project.

What is the license for this code base? Do you mind if I use the core Sudoku engine in another game?

**Comment by dioveath** [comment]
Hi, @Bryan-Legend
Thanks, I'm happy you've found something of value in this project.
And Yes, you can use it free for commercial use, and you can simply give a little bit of space on the credit section. 
Thanks

**Comment by Bryan-Legend** [comment]
Thank you! Will do! Love your code. ❤ It's better than the sudoku in the asset stores.
